apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-db
data:
  POSTGRES_USER: fusionauth
  POSTGRES_DB: fusionauth

---

apiVersion: v1
kind: Secret
metadata:
  name: auth-db
type: Opaque
stringData:
  POSTGRES_PASSWORD: fusionauth

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db
  labels:
    app: auth-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-db

  template:
    metadata:
      name: auth-db
      labels:
        app: auth-db
    spec:
      hostNetwork: true
      containers:
        - name: auth-db
          image: postgres:15-alpine
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: auth-db
            - configMapRef:
                name: auth-db
          ports:
            - containerPort: 5432
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: auth-db
spec:
  selector:
    app: auth-db
  ports:
    - name: db-port
      port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP