name: pr-action
run-name: Pull Request Actions

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3

      - run: ls -la

      - name: Service Name
        id: svc-name
        run: echo "svc=$(echo ${{ github.ref_name }} | cut -d/ -f 2)" >> $GITHUB_OUTPUT

      - name: Test
        uses: 'Rusbenk/rusbeckend/.github/workflows/test.yml'
        with:
          service: ${{ steps.svc-name.outputs.svc }}