name: pr-action
run-name: Pull Request Actions

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  setup:
    uses: ./.github/workflows/setup.yml


  test:
    uses: './.github/workflows/test.yml'
    with:
      service: ${{ jobs.setup.outputs.svc }}