name: pr-action
run-name: Pull Request Actions

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  - name: Fetch Repository
    uses: actions/checkout@v3

  - name: Service Name
    id: svc-name
    run: echo "svc=$(echo ${{ github.ref_name }} | cut -d/ -f 2)" >> $GITHUB_OUTPUT

  - name: Test
    uses: './.github/workflows/test.yml'
    with:
      service: ${{ steps.svc-name.outputs.svc }}