name: setup
run-name: Setting Up

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Setup service
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3

      - name: Service Name
        id: svc-name
        run: echo "svc=$(echo ${{ github.ref_name }} | cut -d/ -f 2)" >> $GITHUB_OUTPUT